### PR TITLE
[RHELC-645] Skip check of latest kernel on OL8.4

### PR DESCRIPTION
**Pull request by hosekadam**
Skip the check on OL 8.4 because there are no available repositories.

https://issues.redhat.com/browse/RHELC-645

### CODE REVIEW

**Comment by r0x0d** [comment]
@hosekadam you will need to adjust the unit_tests as they were made to mock the `releasever` with the complete version and your change is exact the opposite.

**Comment by hosekadam** [comment]
@r0x0d I see, I've run the unit test's locally successfully. But in bad branch...

**Review by SpyTec — APPROVED** [review]

**Review by r0x0d — DISMISSED** [review]

**Comment by r0x0d** [comment]
Just a reminder that https://github.com/oamg/convert2rhel/pull/607 also changes code that this PR touches. Since #607 needs to be merged before the 1.1 release, I would advise changing the unit_test here to reflect the unit test from #607 (just to avoid another rebase/push after we merge #607)

**Comment by kokesak** [comment]
I cherry-picked the https://github.com/oamg/convert2rhel/pull/517/commits/1e0acda35ed30f525e49af63d8331a9f27254140 to see if the fix works for this issue.

**Review by SpyTec — APPROVED** [review]
LGTM

**Review by r0x0d — DISMISSED** [review]
Looks good to me. Can we get an approval from QE? @danmyway.

**Review by danmyway — APPROVED** [review]
LGTM, thanks @hosekadam !

**Comment by r0x0d** [comment]
Oh god. We have a conflict :(

**Review by SpyTec — APPROVED** [review]
Was only a minor conflict related to unit tests. Unit tests are passing so I'm merging

**Pull request merged**
