### PR TITLE
[packit] test in the internal TF

### PR DESCRIPTION
**Pull request by lachmanfrantisek**
- [ ] Wait for the next week to have the internal TF support in the production instance of Packit or [use the staging one](https://github.com/packit/packit-service/issues/649). (The following error from `packit-as-a-service` is because of that.)
- [ ] Check, that the target conversion works as expected (https://github.com/packit/packit-service/pull/1126).

*Btw, I see you use pre-commit. Do you know https://pre-commit.ci ?*

### CODE REVIEW

**Comment by ZhukovGreen** [comment]
@lachmanfrantisek thank you for the contribution. About pre-commit.ci do you have example project which takes advantage of their new ci system?

**Comment by lachmanfrantisek** [comment]
> About pre-commit.ci do you have example project which takes advantage of their new ci system?

We use it for most of [our repositories](https://github.com/packit), e.g. https://github.com/packit/ogr, https://github.com/packit/packit or https://github.com/packit/packit-service

Some bigger hooks like `ansible-lint` do not work, but otherwise, it's really quick and updates your config weekly.

**Comment by lachmanfrantisek** [comment]
@ZhukovGreen The prod update is up and I've enabled your project to use internal TF. Please, take a look.

Note that TF probably does not have an image for `epel-6` (@thrix, is that right?).

Can I do anything else for you here?

**Comment by ZhukovGreen** [comment]
Thx @lachmanfrantisek thank you for your work. I'll adopt our tests and rebase on too of you MR so we can try it all together

**Comment by bocekm** [comment]
> Note that TF probably does not have an image for epel-6 (@thrix, is that right?).

I've removed running tests on CentOS Linux 6 (epel-6 copr chroot) as conversions of that system are not supported.

I've also added running the tests on the supported Oracle Linux 7 and 8.

**Review by bocekm — APPROVED** [review]

**Comment by bocekm** [comment]
Thanks, @lachmanfrantisek. I'll merge this and we'll try how it works with other PR that change the integration tests (e.g. #343 or #321)

**Pull request merged**
