### PR TITLE
add config for Rocky Linux 8

### PR DESCRIPTION
**Pull request by jonathan-sturges**

### CODE REVIEW

**Comment by bocekm** [comment]
@jonathan-sturges, what image are you using for testing?
I've tried https://app.vagrantup.com/rockylinux/boxes/8 but it has just ~400M available at `/` and the conversion fails for not enough space, and it's not partitioned with lvm so I can't easily enlarge it.

**Comment by jonathan-sturges** [comment]
> @jonathan-sturges, what image are you using for testing?
> I've tried https://app.vagrantup.com/rockylinux/boxes/8 but it has just ~400M available at `/` and the conversion fails for not enough space. And it's not partitioned with lvm so I can't easily enlarge it. Or maybe I can but I'm not well-versed in that.

I did most testing on a physical mini desktop system, installed from a Rocky 8 USB stick.  The machine had a 60Gb SSD in it, and I let it auto-partition.
I'll take a look at the image above.  In my experience, it's not hard to grow LVs when an image is provisioned on a larger disk; I've used growpart, pvresize and lvextend -r to do this.

**Comment by jonathan-sturges** [comment]
> @jonathan-sturges, what image are you using for testing?
> I've tried https://app.vagrantup.com/rockylinux/boxes/8 but it has just ~400M available at `/` and the conversion fails for not enough space. And it's not partitioned with lvm so I can't easily enlarge it. Or maybe I can but I'm not well-versed in that.

I played around with Vagrant and was able to do a successful conversion.  The box I tested had a 40Gb root and wasn't using LVM.  (I specified v4.0.0 of the Rocky8 box, so not sure what I did that resulted in a different configuration from yours.)  Nonetheless, I was able to use the Vagrant 'disksize' plugin to expand the virtual disk to 50gb, then used `growpart` and `xfs_growfs` to make the new space usable; Convert2RHEL ran fine after this.

**Comment by r0x0d** [comment]
Rebased and pushed to this PR to make the CI updated. 

Overall, the conversion went smoothly without any errors, but I had to use eurolinux-vagrant/rocky-8 in Vagrant in order to make this work.

**Review by r0x0d — APPROVED** [review]

**Pull request merged**
