### PR TITLE
Introduce packit

### PR DESCRIPTION
**Pull request by bocekm**
- to automate:
  - CD in Copr
  - testing
  - EPEL releases in dist-git

This is a follow up PR after https://github.com/oamg/convert2rhel/pull/11.

TODO:

- [ ] [Run unit tests](https://github.com/oamg/convert2rhel/blob/master/run_unit_tests.sh) for every PR commit
- [x] Build the tool in the [custom Copr (under OAMG group)](https://copr.fedorainfracloud.org/coprs/g/oamg/convert2rhel/), not the packit Copr

### CODE REVIEW

**Comment by bocekm** [comment]
@sturivny, I'd like the copr builds to be created under https://copr.fedorainfracloud.org/coprs/g/oamg/convert2rhel/. It should already work now when https://github.com/packit-service/packit/issues/686 has been fixed. Or do you want to create a separate PR for that?

**Comment by sturivny** [comment]
@bocekm I'm fine with you

**Comment by bocekm** [comment]
@sturivny, I've updated the description with the TODO (unit tests, custom copr repo). Can you please try to take care of that?

**Comment by sturivny** [comment]
@bocekm sure, thanks : )

**Comment by bocekm** [comment]
@sturivny, @lachmanfrantisek, @TomasTomecek, building in the custom copr works. That's great!

The log linked by packit for the RPM build however points to an invalid copr build URL.

The log: https://prod.packit.dev/copr-build/3500/logs
The invalid link in the log: https://copr.fedorainfracloud.org/coprs/@oamg/convert2rhel/build/1321726/
The link that works: https://copr.fedorainfracloud.org/coprs/g/oamg/convert2rhel/build/1321726/

**Comment by bocekm** [comment]
@sturivny, @lachmanfrantisek, @TomasTomecek
Also, the testing farm is trying to install the convert2rhel build from an invalid copr repo URL.

Testing farm log: https://console-testing-farm.apps.ci.centos.org/pipeline/1bb7bded-36e2-4b9b-b34f-47333aaf418e
It tries to install the pkg from: https://copr.fedorainfracloud.org/coprs/@oamg/oamg-convert2rhel-27/repo/epel-6/oamg-convert2rhel-27-epel-6.repo
It should be installing it from: https://copr.fedorainfracloud.org/coprs/g/oamg/convert2rhel/repo/epel-6/group_oamg-convert2rhel-epel-6.repo

**Comment by sturivny** [comment]
@bocekm I'll contact testing farm team about that issue

**Comment by lachmanfrantisek** [comment]
> @bocekm I'll contact testing farm team about that issue

That's maybe our fault -- let me check that.

**Comment by lachmanfrantisek** [comment]
@bocekm I'll take a look, thanks for checking that!

**Comment by csomh** [comment]
There seem to be 2 issues here:

1. The COPR build URL is generated by Packit by CoprHelper.copr_web_build_url, and it's a format string, which obviously is very fragile. Unfortunately build objects provided by the Copr Python API don't have this value (or I was looking at the wrong place). The really nice solution here would be to make Copr API provide this value.

2. The copr repo url is worng b/c we always use `default_project_name` when sending `copr-repo-name` to Testing Farm.

**Comment by thrix** [comment]
werks :) kudos to @csomh for the fix :)

**Comment by bocekm** [comment]
@sturivny, let's deal with the unit tests under https://github.com/oamg/convert2rhel/pull/28. I'm merging this now, it looks solid.

**Pull request merged**
