### PR TITLE
[RHELC-889] Make TASK log messages consistent

### PR DESCRIPTION
**Pull request by bocekm**
Some of the log messages were using continous tense, some present tense. There was more of the messages with the present tense so this commit transforms all the messages to the present tense.

Jira Issue: [RHELC-889](https://issues.redhat.com/browse/RHELC-889)

Checklist
- [x] PR meets acceptance criteria specified in the Jira issue
- [x] PR has been tested manually in a VM (either author or reviewer)
- [x] Jira issue has been made public if possible
- [x] `[RHELC-889]` is part of the PR title 
- [x] Code and tests are documented properly
- [x] The commits are squashed to as few commits as possible (without losing data) 
- [ ] When merged: Jira issue has been updated to `Release Pending`

### CODE REVIEW

**Comment by SpyTec** [comment]
Do we want present tense? Is that what IBM style doc says if they have anything about it?

**Review by SpyTec — APPROVED** [review]

**Review by SpyTec — CHANGES_REQUESTED** [review]
Few integration test failures 
```
=================================== FAILURES ===================================
__________________ test_backup_os_release_wrong_registartion ___________________

shell = <function shell.<locals>.factory at 0x7fab7fbcd158>
convert2rhel = <function convert2rhel.<locals>.factory at 0x7fab7fbcd400>

    def test_backup_os_release_wrong_registartion(shell, convert2rhel):
        """
        Verify that the os-release file is restored when the satellite registartion fails.
        Refrence issue: RHELC-51
        """
        assert shell("find /etc/os-release").returncode == 0
    
        with convert2rhel("-y --no-rpm-va -k wrong_key -o rUbBiSh_pWd --debug --keep-rhsm") as c2r:
            c2r.expect("Unable to register the system through subscription-manager.")
>           c2r.expect("Restoring /etc/os-release from backup")

test_backup_release.py:103: 
```

```
=================================== FAILURES ===================================
_____________ test_latest_kernel_check_with_exclude_kernel_option ______________

shell = <function shell.<locals>.factory at 0x7fb9c81e32f0>
convert2rhel = <function convert2rhel.<locals>.factory at 0x7fb9c81e3400>

    @pytest.mark.yum_excld_kernel
    def test_latest_kernel_check_with_exclude_kernel_option(shell, convert2rhel):
        """
        Define `exclude=kernel` in /etc/yum.conf and verify, the conversion is not inhibited with:
        'CRITICAL - Could not find any kernel from repositories to compare against the loaded kernel.'
        """
    
        yum_config = "/etc/yum.conf"
        backup_dir = "/tmp/config-backup"
        config = configparser.ConfigParser()
        config.read(yum_config)
        exclude_option = "kernel kernel-core"
    
        assert shell(f"mkdir {backup_dir}").returncode == 0
    
        assert shell(f"cp {yum_config} {backup_dir}").returncode == 0
        # If there is already an `exclude` section, append to the existing value
        if config.has_option("main", "exclude"):
            pre_existing_value = config.get("main", "exclude")
            config.set("main", "exclude", f"{pre_existing_value} kernel kernel-core")
        else:
            config.set("main", "exclude", "kernel kernel-core")
    
        with open(yum_config, "w") as configfile:
            config.write(configfile, space_around_delimiters=False)
    
        assert config.has_option("main", "exclude")
        assert exclude_option in config.get("main", "exclude")
    
        # Run the conversion and verify, that it goes past the latest kernel check
        # if so, inhibit the conversion
        with convert2rhel("-y --debug --no-rpm-va") as c2r:
>           c2r.expect("Prepare: Checking if the loaded kernel version is the most recent")

test_latest_kernel_check.py:84: 
```

**Comment by r0x0d** [comment]
Updated the integration test messages to reflect the changes in the source code.

**Comment by r0x0d** [comment]
Test failures doesn't seem to be related. Re-triggering them just in case

**Review by SpyTec — APPROVED** [review]

**Pull request merged**
