### PR TITLE
Pylint fix warnings: [C0103 invalid-name]

### PR DESCRIPTION
**Pull request by sturivny**
As discussed in https://github.com/oamg/convert2rhel/pull/50#issuecomment-631512340
Disabled pylint checks for the:
```
[C0103 invalid-name] Constant name "tool_opts" doesn't conform to UPPER_CASE naming style File: convert2rhel/toolopts.py, line 226, in print_non_interactive_opts
[C0103 invalid-name] Constant name "tool_opts" doesn't conform to UPPER_CASE naming style File: convert2rhel/toolopts.py, line 255, in 
[C0103 invalid-name] Constant name "system_info" doesn't conform to UPPER_CASE naming style File: convert2rhel/systeminfo.py, line 161, in 
```
by adding comment `# pylint: disable=invalid-name  # noqa`

### CODE REVIEW

**Comment by sturivny** [comment]
Will take a look

**Comment by sturivny** [comment]
@bocekm updated. Now looks like everything fine except looong names :)

**Comment by sturivny** [comment]
Fixed!

**Comment by ZhukovGreen** [comment]
@bocekm maybe because py3 version keeps evolving...

**Pull request merged**
