### PR TITLE
#PR - Fixed the subscription.py file with to libdnf-plugin and not dnf-plugin for RHEL 9 

### PR DESCRIPTION
**Pull request by sp4wnr0ot**
Jira Issues: [RHELC-](https://issues.redhat.com/browse/RHELC-)

Checklist

- [x] PR has been tested manually in a VM (either author or reviewer)
- [ ] Jira issue has been made public if possible
- [ ] `[RHELC-]` is part of the PR title 
- [ ] GitHub label has been added to help with Release notes 
- [x] PR title explains the change from the user's point of view
- [x] Code and tests are documented properly
- [x] The commits are squashed to as few commits as possible (without losing data) 
- [ ] When merged: Jira issue has been updated to `Release Pending` if relevant

### CODE REVIEW

**Comment by bocekm** [comment]
Thanks, @sp4wnr0ot. You're targeting the PR to land in the main branch which doesn't have any RHEL 9-related code yet. The change needs to land in the https://github.com/oamg/convert2rhel/pull/860. One option would be to create a PR against @SpyTec's https://github.com/SpyTec/convert2rhel/tree/feat/el9-conversions branch in their fork. But let me take that, I'll make the change in the PR #860.

**Comment by bocekm** [comment]
https://github.com/oamg/convert2rhel/pull/860/commits/a5ad8f9ef1b08e867feb2daed6d0a856b981c4dd

**Comment by SpyTec** [comment]
I should probably make my pr into a branch in this repo. It will be better to contribute, I'll do it soon

**Comment by sp4wnr0ot** [comment]
> 

Ok, Cool.

**Pull request closed without merging**
