### PR TITLE
[RHELC-1760] Make post-conversion analysis summary clearer

### PR DESCRIPTION
**Pull request by bocekm**
I was not sure what "No changes needed" means (changes to do by the tool or myself?).
IMHO "No action required" is clearer.

Jira Issues:

- [RHELC-1760](https://issues.redhat.com/browse/RHELC-1760)

Checklist

- [x] PR has been tested manually in a VM (either author or reviewer)
- [x] Jira issue has been made public if possible
- [x] `[RHELC-]` or `[HMS-]` is part of the PR title 
- [x] Label depicting the kind of PR it is 
- [x] PR title explains the change from the user's point of view
- [x] Code and tests are documented properly
- [x] The commits are squashed to as few commits as possible (without losing data) 
- [ ] When merged: Jira issue has been updated to `Release Pending` if relevant

### CODE REVIEW

**Review by Venefilyn — APPROVED** [review]

**Review by hosekadam — APPROVED** [review]
Looks good. Just this will need some changes in integration tests as somewhere is `No changes needed` expected e.g.:
` /tests/integration/tier0/non-destructive/assessment-report/successful_report` or `/tests/integration/tier0/non-destructive/assessment-report/failures_and_skips_in_report`

**Review by danmyway — APPROVED** [review]
Looks good!

**Pull request merged**
