### PR TITLE
[RHELC-1673] Include all reports in post-conversion report

### PR DESCRIPTION
**Pull request by hosekadam**
Include all reports in post-conversion report to be consistent with behavior of the analysis report, where all the reports are included.

Jira Issues:

- [RHELC-1673](https://issues.redhat.com/browse/RHELC-1673)

Checklist

- [ ] PR has been tested manually in a VM (either author or reviewer)
- [x] Jira issue has been made public if possible
- [x] `[RHELC-]` or `[HMS-]` is part of the PR title 
- [ ] GitHub label has been added to help with Release notes 
- [ ] PR title explains the change from the user's point of view
- [ ] Code and tests are documented properly
- [ ] The commits are squashed to as few commits as possible (without losing data) 
- [ ] When merged: Jira issue has been updated to `Release Pending` if relevant

### CODE REVIEW

**Review by Venefilyn — DISMISSED** [review]
IMO underlying `_report()` should be refactored completely so that we are using a dict with levels and name, just like how python logging works. I.e. assigning a number to each level

On that note too, `include_all_reports` isn't very telling of what it means. I'd go for refactoring it completely with a key-value pair instead like mentioned above

**Review by pr-watson — APPROVED** [review]
Looks good to me!

**Comment by r0x0d** [comment]
> IMO underlying `_report()` should be refactored completely so that we are using a dict with levels and name, just like how python logging works. I.e. assigning a number to each level
> 
> On that note too, `include_all_reports` isn't very telling of what it means. I'd go for refactoring it completely with a key-value pair instead like mentioned above

We have a specific ticket for that refactor. It is not viable to handle this as part of this PR I would say.

**Comment by Venefilyn** [comment]
> We have a specific ticket for that refactor. It is not viable to handle this as part of this PR I would say.

That's fine. We don't even know what action statuses we have atm (well we do but like, there is nothing preventing us from typing WARMING instead of WARNING somewhere AFAIK) which isn't great when saying yeah lets include everything

@pr-watson @hosekadam could either of you create a Jira issue about this though? Making actions type safe and having a key-value dict between levels and their value

**Comment by hosekadam** [comment]
> could either of you create a Jira issue about this though? Making actions type safe and having a key-value dict between levels and their value
@Venefilyn I think there is some checking, when I tried to create a wrong level, it crashed on the check. Maybe it's this https://github.com/oamg/convert2rhel/blob/main/convert2rhel/actions/__init__.py#L366 ? But I'm not sure if that's what you meant. Also I see some mapping there: https://github.com/oamg/convert2rhel/blob/main/convert2rhel/actions/__init__.py#L68

**Comment by pr-watson** [comment]
> > could either of you create a Jira issue about this though? Making actions type safe and having a key-value dict between levels and their value
> 
> @Venefilyn I think there is some checking, when I tried to create a wrong level, it crashed on some check. Maybe it's this https://github.com/oamg/convert2rhel/blob/main/convert2rhel/actions/__init__.py#L366 ? But I'm not sure if that's what you meant. Also I see some mapping there: https://github.com/oamg/convert2rhel/blob/main/convert2rhel/actions/__init__.py#L68

Yes those are the correct places @hosekadam

**Pull request merged**
