### PR TITLE
[RHELC-1167] tests/Slim down PR test suite

### PR DESCRIPTION
**Pull request by danmyway**
* slim down the suite needed for pull request to be merged

Jira Issues: [RHELC-1167](https://issues.redhat.com/browse/RHELC-1167)

Checklist

- [x] PR has been tested manually in a VM (either author or reviewer)
- [x] Jira issue has been made public if possible
- [x] `[RHELC-]` is part of the PR title 
- [x] GitHub label has been added to help with Release notes 
- [x] PR title explains the change from the user's point of view
- [x] Code and tests are documented properly
- [x] The commits are squashed to as few commits as possible (without losing data) 
- [x] When merged: Jira issue has been updated to `Release Pending` if relevant

### CODE REVIEW

**Comment by danmyway** [comment]
Label commenter won't work at this point, as it's pointing to the `pull_request_target`, which doesn't have the `tests-run-sanity` label configured yet.

**Comment by kokesak** [comment]
Sanity tests are now running around 25 minutes which is great! Thanks @danmyway

**Review by kokesak — APPROVED** [review]

**Pull request merged**
