### PR TITLE
Follow-up on the comments from PR#458

### PR DESCRIPTION
**Pull request by r0x0d**
This PR introduces some comments that were left behind from PR#458 that
were not such a big deal to merge it without them.

Signed-off-by: Rodolfo Olivieri <rolivier@redhat.com>

### CODE REVIEW

**Comment by r0x0d** [comment]
@kokesak feel free to address any of the comments left behind in the #458.

**Comment by kokesak** [comment]
I addressed all the left comments there. Let's wait for the tests to finish.

**Review by abadger — APPROVED** [review]
Simple changes that look good.  Approved.

**Comment by r0x0d** [comment]
Merging this. Thanks!

**Pull request merged**
