### PR TITLE
Pylint fix bad-whitespace, wrong-import-order, bad-continuation

### PR DESCRIPTION
**Pull request by sturivny**
[C0326 bad-whitespace] No space allowed around keyword argument assignment
[C0411 wrong-import-order] standard import
[C0330 bad-continuation] Wrong continued indentation

### CODE REVIEW

**Comment by fellipeh** [comment]
@sturivny  please rebase to proceed and merge :)

**Comment by sturivny** [comment]
Rebased!

**Comment by bocekm** [comment]
Please rebase. I'll reapprove and merge right after that.

**Comment by sturivny** [comment]
> Please rebase. I'll reapprove and merge right after that.

Done!

**Pull request merged**
