### PR TITLE
Pylint fix C0103 invalid Class name

### PR DESCRIPTION
**Pull request by sturivny**
Class names should follow the UpperCaseCamelCase

### CODE REVIEW

**Comment by SpyTec** [comment]
I noticed in the pylint that there are a few more cases of C0103, specifically with variables. Do we want to tackle this in a separate PR?

**Comment by sturivny** [comment]
@SpyTec 
> I noticed in the pylint that there are a few more cases of C0103, specifically with variables. Do we want to tackle this in a separate PR?

I don't know. For me, it looks good. 
I'd rather add an exception to the pylint config file.

**Comment by bocekm** [comment]
Some of the C0103 messages are because the function name is longer than 30 chars. I'm not a fan of this rule. I prefer longer but descriptive function name rather than function name that doesn't clearly tell me what the function does.
For these messages I'd the ignore comment.

I guess that you can change constants to uppercase and classes to PascalCase.

**Comment by sturivny** [comment]
Sure, will do that in other commits. 
There is the first one https://github.com/oamg/convert2rhel/pull/53

**Pull request merged**
