### PR TITLE
[RHELC-1717] Fix the latest RHEL kernel not being set as default when converting from CentOS Stream 9

### PR DESCRIPTION
**Pull request by hosekadam**
* simplify the kernel (re-)installation 
* check if any RHEL kernel got installed during the main transaction, if not, handle the same version conflict
* try to update the installed kernel in every case

Jira Issues:

- [RHELC-1717](https://issues.redhat.com/browse/RHELC-1717)

Checklist

- [x] PR has been tested manually in a VM (either author or reviewer)
- [x] Jira issue has been made public if possible
- [x] `[RHELC-]` or `[HMS-]` is part of the PR title 
- [x] GitHub label has been added to help with Release notes 
- [x] PR title explains the change from the user's point of view
- [x] Code and tests are documented properly
- [ ] The commits are squashed to as few commits as possible (without losing data) 
- [ ] When merged: Jira issue has been updated to `Release Pending` if relevant

### CODE REVIEW

**Comment by bocekm** [comment]
I've manually tested the current state of this PR on a conversion of CentOS Stream 9 and there's been no issues with kernel.
RHEL kernel installed:
- kernel-5.14.0-503.14.1.el9_5.x86_64
Stream kernels removed:
- kernel-0:5.14.0-514.el9.x86_64
- kernel-0:5.14.0-529.el9.x86_64

Rebooting to the RHEL kernel went ok.

**Review by danmyway — APPROVED** [review]
QE ack

**Review by bocekm — APPROVED** [review]

**Pull request merged**
