### PR TITLE
[RHELC-1463] Enhance the internet connection check test

### PR DESCRIPTION
**Pull request by kokesak**
Add a scenario where the internet connection check
fails but the analysis finishes without issue.

Jira Issues: [RHELC-1463](https://issues.redhat.com/browse/RHELC-1463)

Checklist

- [ ] PR has been tested manually in a VM (either author or reviewer)
- [ ] Jira issue has been made public if possible
- [ ] `[RHELC-]` is part of the PR title 
- [ ] GitHub label has been added to help with Release notes 
- [ ] PR title explains the change from the user's point of view
- [ ] Code and tests are documented properly
- [ ] The commits are squashed to as few commits as possible (without losing data) 
- [ ] When merged: Jira issue has been updated to `Release Pending` if relevant

### CODE REVIEW

**Comment by danmyway** [comment]
> /packit build

do it

**Comment by kokesak** [comment]
Tests:

- CentOS7 http://artifacts.osci.redhat.com/testing-farm/5dc48c91-03d9-4cfb-87ed-2d41fa6a07c1
- CentOS8 http://artifacts.osci.redhat.com/testing-farm/52fc6fd6-0bf9-4218-9130-97b91a338b5e
- OL7 http://artifacts.osci.redhat.com/testing-farm/21aaa1ca-ab4f-4690-9bc2-f4441d18993d
- OL8.9 http://artifacts.osci.redhat.com/testing-farm/9e39c01a-49b0-4825-b1e3-112fcb8bd960
- Alma8.9 http://artifacts.osci.redhat.com/testing-farm/7f3443ba-cd43-4aa2-85fe-7b148e10e1fc
- Rocky8.9 http://artifacts.osci.redhat.com/testing-farm/3b0721c8-4790-4542-abfb-d40920ab87a5

**Review by danmyway — APPROVED** [review]
Very nice, thanks @kokesak

**Comment by kokesak** [comment]
Closing as the https://github.com/oamg/convert2rhel/pull/1181 drops the internet connection.

**Pull request closed without merging**
