### PR TITLE
PR just to see if head is currently passing CI

### PR DESCRIPTION
**Pull request by abadger**
Jira Issue: [RHELC-]()

Checklist
- [ ] PR meets acceptance criteria specified in the Jira issue
- [ ] PR has been tested manually in a VM (either author or reviewer)
- [ ] Jira issue has been made public if possible
- [ ] `[RHELC-]` is part of the PR title 
- [ ] Code and tests are documented properly
- [ ] The commits are squashed to as few commits as possible (without losing data) 
- [ ] When merged: Jira issue has been updated to `Release Pending`

### CODE REVIEW

**Comment by SpyTec** [comment]
The issues that remain seem to be about the tests themselves, so we can close this PR right_

**Comment by danmyway** [comment]
> The issues that remain seem to be about the tests themselves, so we can close this PR right?

Well the tests dispatched by Pakit all passed, GitHub action dispatched tests failed.
I would keep it for investigation purposes, @SpyTec

**Comment by r0x0d** [comment]
@abadger do we still need this PR?

**Comment by SpyTec** [comment]
Since it relates to running TFT through GitHub Actions which we now removed I'll go ahead and close

**Pull request closed without merging**
