### PR TITLE
Remove pre check from ci

### PR DESCRIPTION
**Pull request by abadger**
Jira Issues: [RHELC-](https://issues.redhat.com/browse/RHELC-)

Checklist

- [ ] PR has been tested manually in a VM (either author or reviewer)
- [ ] Jira issue has been made public if possible
- [ ] `[RHELC-]` is part of the PR title 
- [ ] GitHub label has been added to help with Release notes 
- [ ] PR title explains the change from the user's point of view
- [ ] Code and tests are documented properly
- [ ] The commits are squashed to as few commits as possible (without losing data) 
- [ ] When merged: Jira issue has been updated to `Release Pending` if relevant

### CODE REVIEW

**Review by r0x0d — APPROVED** [review]

**Comment by SpyTec** [comment]
Seems like there is an issue with rebase here

**Comment by r0x0d** [comment]
> Seems like there is an issue with rebase here

That's fine! We will only merge this PR after we finish everything, and we want to merge pre-check to main!

**Comment by abadger** [comment]
Rebased.  Should be ready again.

**Comment by abadger** [comment]
It's interesting that you didn't have access to push to my branch.  I have `Allow edits and access to secrets by maintainers` checked on this PR so github should allow it.

**Review by r0x0d — APPROVED** [review]

**Pull request merged**
