### PR TITLE
Add basic sanity checks

### PR DESCRIPTION
**Pull request by danmyway**
As a part of morf tool decommission add some basic sanity checks to the
integration tests using tmt.
- check for manpage
- basic smoke test

Rename the test scenario previously named as check-privileges and add
mentioned above.

### CODE REVIEW

**Review by mkluson — DISMISSED** [review]

**Comment by r0x0d** [comment]
@danmyway the file `tests/integration/tier0/basic-sanity-checks/test_basic_sanity_checks` has no `.py` extension, is this on purpose?

**Review by r0x0d — DISMISSED** [review]

**Review by mkluson — APPROVED** [review]

**Review by kokesak — DISMISSED** [review]
Looks good, @danmyway just try if using the `shell` function works also for adding the new user. If not than you can leave it as it is.

**Comment by danmyway** [comment]
> Looks good, @danmyway just try if using the `shell` function works also for adding the new user. If not than you can leave it as it is.

Yep, I'll try if calling the `shell()` will work as expected, if so, I'll change it accordingly.
IIRC we used the `os.system()` to do it in a 'more pythonic way', although as resolved [here](https://github.com/oamg/convert2rhel/pull/356#discussion_r853218047), calling the `shell()` is okay too.

**Comment by danmyway** [comment]
No issues with calling the `shell()` function.
All the `os.system()` calls were changed.

**Review by kokesak — APPROVED** [review]
LGTM, the failing OL8 tests are due to satellite content that is missing for 8.6

**Review by r0x0d — APPROVED** [review]

**Comment by danmyway** [comment]
The failing tests were the one with the satellite issue now resolved, it should pass now, @r0x0d

**Comment by kokesak** [comment]
All passed. Good job @danmyway!

**Pull request merged**
