### PR TITLE
Integration tests: address changes in reported strings

### PR DESCRIPTION
**Pull request by kokesak**
A few recent PRs added more specific error messages that are being reported. Address those changes in integration tests as well.

### CODE REVIEW

**Comment by kokesak** [comment]
All failing tests are due to the non-latest kernel present on satellite repo. OL8 fails due to a known issue with

firewalld - https://issues.redhat.com/browse/RHELC-1180

and alma8.8 `shim-x64`: https://issues.redhat.com/browse/RHELC-1190

**Review by danmyway — APPROVED** [review]
Looking good, thank you @kokesak

**Comment by kokesak** [comment]
No errors are related to this PR. Merging

**Pull request merged**
