### PR TITLE
Fix typo in the pkghandler

### PR DESCRIPTION
**Pull request by sturivny**

### CODE REVIEW

**Comment by sturivny** [comment]
The idea behind this PR is to check CI `pipeline-state-reporter`

**Review by ZhukovGreen — DISMISSED** [review]

**Comment by ZhukovGreen** [comment]
@sturivny WIP?

**Comment by ZhukovGreen** [comment]
@sturivny could you please explain this `CI pipeline-state-reporter`. Like, I don't know, the state before and after MR (some pictures or anything else)

**Review by fellipeh — DISMISSED** [review]

**Review by fellipeh — COMMENTED** [review]
LGTM after all green @sturivny  please rebase

**Review by bocekm — APPROVED** [review]

**Comment by bocekm** [comment]
I did not expect the tests to fail on this, but they did :) Fix: https://github.com/oamg/convert2rhel/pull/183

**Pull request merged**
