### PR TITLE
[DRAFT] Try Label Commenter GitHub Action

### PR DESCRIPTION
**Pull request by danmyway**
* use labels to add comments to trigger test suites

Jira Issues: [RHELC-](https://issues.redhat.com/browse/RHELC-)

Checklist

- [ ] PR has been tested manually in a VM (either author or reviewer)
- [ ] Jira issue has been made public if possible
- [ ] `[RHELC-]` is part of the PR title 
- [ ] GitHub label has been added to help with Release notes 
- [ ] PR title explains the change from the user's point of view
- [ ] Code and tests are documented properly
- [ ] The commits are squashed to as few commits as possible (without losing data) 
- [ ] When merged: Jira issue has been updated to `Release Pending` if relevant

### CODE REVIEW

**Comment by SpyTec** [comment]
Could merge to a branch in the repo in case there is some issues with this coming from a fork

**Comment by danmyway** [comment]
> Could merge to a new branch in the repo in case there is some issues with this coming from a fork

I think I will do that, thanks for the suggestion @SpyTec !

**Review by SpyTec — APPROVED** [review]

**Comment by danmyway** [comment]
@SpyTec, @r0x0d The action fails with `Error: Action failed with error "Resource not accessible by integration"`.
Would you happen to know, how to make it work?

**Comment by SpyTec** [comment]
That's why I'd try to merge into a new branch in the repo go see if it's that

**Comment by danmyway** [comment]
I have done that, with no luck so far.

**Comment by SpyTec** [comment]
> I have done that, with no luck so far.

@danmyway see https://github.com/oamg/convert2rhel/pull/872

**Comment by danmyway** [comment]
Oooh, I see, I was just being stupid, thanks for fixing that @SpyTec !

**Pull request closed without merging**
