### PR TITLE
Do not require /etc/os-release to be present

### PR DESCRIPTION
**Pull request by bocekm**
The tool was tracebacking when the /etc/os-release file was not present (at least on CentOS Linux 6 and 7):
```
Backing up None.
[12/03/2021 20:20:16] DEBUG - Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/convert2rhel/main.py", line 94, in main
    redhatrelease.os_release_file.backup()
  File "/usr/lib/python2.6/site-packages/convert2rhel/utils.py", line 527, in backup
    if os.path.isfile(self.filepath):
  File "/usr/lib64/python2.6/genericpath.py", line 29, in isfile
    st = os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found

No changes were made to the system.
```

Fixes: https://github.com/oamg/convert2rhel/pull/357
Related: https://issues.redhat.com/browse/OAMG-5457

### CODE REVIEW

**Comment by bocekm** [comment]
@kokesak, please cover this by an integration test verifying that:
- not having /etc/os-release file causes no issue to the conversion process - it continues without stopping, and simply not backing up the file
- not having /etc/system-release files ends up with the tool exiting with `SystemExit: Error: Unable to find the /etc/system-release file containing the OS name and version`

**Review by SpyTec — APPROVED** [review]

**Review by r0x0d — DISMISSED** [review]

**Review by r0x0d — DISMISSED** [review]

**Review by SpyTec — DISMISSED** [review]

**Comment by kokesak** [comment]
Passing tests are reported by packit.
Failures with released version for the backup file and `/etc/system-removal`:
OL8: http://artifacts.osci.redhat.com/testing-farm/45b39414-413c-4e14-bc52-7ba7471ccf88/
OL7: http://artifacts.osci.redhat.com/testing-farm/78dc8648-7b7a-4c84-bbb1-b3690aecf11d/
C7: http://artifacts.osci.redhat.com/testing-farm/6033f325-c6a4-42f0-81e7-207d799c2a7f/
C8: http://artifacts.osci.redhat.com/testing-farm/0be74d8c-33a6-4249-9d27-29d7ae4d68ab/

**Review by SpyTec — APPROVED** [review]

**Review by r0x0d — APPROVED** [review]

**Pull request merged**
