### PR TITLE
feat: Enforce convert2rhel styling

### PR DESCRIPTION
**Pull request by SpyTec**
This adds a simply sed replace to style everything to convert2rhel

Jira Issues: [RHELC-](https://issues.redhat.com/browse/RHELC-)

Checklist

- [ ] PR has been tested manually in a VM (either author or reviewer)
- [ ] Jira issue has been made public if possible
- [ ] `[RHELC-]` is part of the PR title 
- [ ] GitHub label has been added to help with Release notes 
- [ ] PR title explains the change from the user's point of view
- [ ] Code and tests are documented properly
- [ ] The commits are squashed to as few commits as possible (without losing data) 
- [ ] When merged: Jira issue has been updated to `Release Pending` if relevant

### CODE REVIEW

**Comment by abadger** [comment]
This looks like what we discussed in cabal.  Two questions:
* Should we run this by Miriam?  I know this is upstream documentation rather than downstream but she might still be interested/have some insight.
* Do we need a way to list exceptions?  I wondered this from seeing convert2rhel as the first word in a title in the changes here. (Another time an exception might be needed is if we talk about the downstream here. (For instance, everything about the rpm repository is talking about downstream).

**Comment by SpyTec** [comment]
Should we change the style for overall to be Convert2RHEL instead? @pr-watson @bocekm

**Comment by bocekm** [comment]
I don't have a strong opinion. Having Convert2RHEL everywhere is fine with me, except perhaps this one place:
https://github.com/oamg/convert2rhel/pull/913/files#diff-ee7acced587f520be7a8a7f4d709f93274fe995c84c20f564e3de8c93b7d6202R218-R219

**Comment by SpyTec** [comment]
Closing for now in favor of a future PR

**Pull request closed without merging**
