### PR TITLE
[RHELC-842] [DRAFT] Pre assessment

### PR DESCRIPTION
**Pull request by abadger**
Implement a pre-assessment sub-command for convert2rhel

Jira Issue: [RHELC-842](https://issues.redhat.com/browse/RHELC-842)

Checklist
- [ ] PR meets acceptance criteria specified in the Jira issue
- [ ] PR has been tested manually in a VM (either author or reviewer)
- [ ] Jira issue has been made public if possible
- [x] `[RHELC-]` is part of the PR title 
- [ ] Code and tests are documented properly
- [ ] The commits are squashed to as few commits as possible (without losing data) 
- [ ] When merged: Jira issue has been updated to `Release Pending`

### CODE REVIEW

**Comment by abadger** [comment]
This is a *very* early draft of the work.  @r0x0d and I are going to work on this together so I'm opening this so we can figure out how to best collaborate with each other.

**Comment by SpyTec** [comment]
The linked issue is the spike itself. When you have time, can you mark that one complete and open a new one for implementation. Just bring up the MVP for the acceptance criteria

**Comment by abadger** [comment]
Closing this.  @r0x0d and I are going to be collaborating on this feature and we're going to work from a new branch in the oamg/convert2rhel repository rather than the one from my repository.

**Comment by SpyTec** [comment]
Just removed issue since the Jira issue is a spike

**Pull request closed without merging**
