### PR TITLE
[RHELC-1373] Reduce timeout for the internet connectivity check

### PR DESCRIPTION
**Pull request by larsbu**
Solves https://github.com/oamg/convert2rhel/issues/1047

Jira Issues: [RHELC-1373](https://issues.redhat.com/browse/RHELC-1373)

Checklist

- [x] PR has been tested manually in a VM (either author or reviewer)
- [x] Jira issue has been made public if possible
- [x] `[RHELC-]` is part of the PR title 
- [x] GitHub label has been added to help with Release notes 
- [x] PR title explains the change from the user's point of view
- [x] Code and tests are documented properly
- [x] The commits are squashed to as few commits as possible (without losing data) 
- [ ] When merged: Jira issue has been updated to `Release Pending` if relevant

### CODE REVIEW

**Comment by larsbu** [comment]
Tested with CentOS7 VM and route to an non existing gateway:
(system has only v4 default route)

````
bash-4.2$ grep urllib /usr/lib/python2.7/site-packages/convert2rhel/systeminfo.py
from six.moves import configparser, urllib
            response = urllib.request.urlopen(CHECK_INTERNET_CONNECTION_ADDRESS, timeout=15)
        except urllib.error.URLError as err:

bash-4.2$ host static.redhat.com
static.redhat.com is an alias for static.redhat.com.edgekey.net.
static.redhat.com.edgekey.net is an alias for e1890.dscx.akamaiedge.net.
e1890.dscx.akamaiedge.net has address 2.17.181.33
e1890.dscx.akamaiedge.net has IPv6 address 2a02:26f0:1700:382::762
e1890.dscx.akamaiedge.net has IPv6 address 2a02:26f0:1700:393::762

bash-4.2$ sudo ip route add 2.17.181.33 via 10.10.10.10

bash-4.2$ sudo /usr/bin/convert2rhel --disable-submgr --enablerepo RHEL* --debug
....
[2024-01-26T11:39:21+0000] DEBUG - Booted kernel VRA (version, release, architecture): 3.10.0-1160.105.1.el7.x86_64
Checking internet connectivity using address 'https://static.redhat.com/test/rhel-networkmanager.txt'.
WARNING - There was a problem while trying to connect to 'https://static.redhat.com/test/rhel-networkmanager.txt' to check internet connectivity. This could be due to the host being offline, or the network blocking access to the endpoint... Some checks and actions will be skipped.
[2024-01-26T11:39:36+0000] DEBUG - Failed to retrieve data from host, reason: [Errno 101] Network is unreachable
....
````

**Review by r0x0d — APPROVED** [review]
Hi, @larsbu! Thanks for your first contribution! 

They look good. Will merge it as soon as possible.

**Comment by SpyTec** [comment]
Thanks again @larsbu!

**Pull request merged**
