### PR TITLE
[RHELC-1109] Try Label Commenter GitHub Action

### PR DESCRIPTION
**Pull request by SpyTec**
* use labels to add comments to trigger test suites

Jira Issues: [RHELC-1109](https://issues.redhat.com/browse/RHELC-1109)

Checklist

- [x] PR has been tested manually in a VM (either author or reviewer)
- [x] Jira issue has been made public if possible
- [x] `[RHELC-]` is part of the PR title 
- [x] GitHub label has been added to help with Release notes 
- [x] PR title explains the change from the user's point of view
- [x] Code and tests are documented properly
- [x] The commits are squashed to as few commits as possible (without losing data) 
- [ ] When merged: Jira issue has been updated to `Release Pending` if relevant

### CODE REVIEW

**Comment by danmyway** [comment]
Hi, there.

This PR does not require integration tests to be run.

---

> This is an automated comment created by the [peaceiris/actions-label-commenter]. Responding to the bot or mentioning it won't have any effect.

[peaceiris/actions-label-commenter]: https://github.com/peaceiris/actions-label-commenter

<div align="right"><a href="https://github.com/oamg/convert2rhel/actions/runs/5656138880">Log</a> | <a href="https://github.com/peaceiris/actions-label-commenter#readme">Bot Usage</a></div>

**Comment by SpyTec** [comment]
> Cool, the action does its part, we just need to fix the access issues. On a different note, @SpyTec would you be fine with adding another variation of Enforce PR labels with regard to the test related labels?

@danmyway yep, totally fine with that

**Comment by danmyway** [comment]
This PR does not require integration tests to be run.



<div align="right"><a href="https://github.com/oamg/convert2rhel/actions/runs/5657014226">Log</a> | <a href="https://github.com/peaceiris/actions-label-commenter#readme">Bot Usage</a></div>

**Comment by danmyway** [comment]
@kokesak, @pholica you can test out the functionality by replacing `tests-skip` by `tests-run-tier0` label, as you wish.

**Review by kokesak — APPROVED** [review]
Looks amazing, great success @danmyway!. Plus 1 for the bot and its name. Let's wait for @pholica thoughts

**Comment by danmyway** [comment]
Trying the packit build command to see if that will trigger the test jobs

**Pull request merged**
