### PR TITLE
[RHELC-1598] Add EL9 repofile url to convert2rhel latest check

### PR DESCRIPTION
**Pull request by pr-watson**
This PR adds the new CDN repo for publishing convert2rhel on EL9. A correction to the diagnosis field in one of the repo.py results was also made. 

Jira Issues:

- [RHELC-1598](https://issues.redhat.com/browse/RHELC-1598)

Checklist

- [ ] PR has been tested manually in a VM (either author or reviewer)
- [ ] Jira issue has been made public if possible
- [ ] `[RHELC-]` or `[HMS-]` is part of the PR title 
- [ ] GitHub label has been added to help with Release notes 
- [ ] PR title explains the change from the user's point of view
- [ ] Code and tests are documented properly
- [ ] The commits are squashed to as few commits as possible (without losing data) 
- [ ] When merged: Jira issue has been updated to `Release Pending` if relevant

### CODE REVIEW

**Review by r0x0d — APPROVED** [review]

**Review by bocekm — APPROVED** [review]

**Comment by Venefilyn** [comment]
Failing integration tests looked like flakes, merging

**Pull request merged**
