### PR TITLE
Feature/use logger instead of custom logger

### PR DESCRIPTION
**Pull request by ZhukovGreen**
This merge request introduces a set of fixes and improvements to the app logger facility.

Fixes:

1. Testing session logger was different from the logger during the app run (not an instance of CustomLogger etc.). This makes invisible CustomLogger functionality (i.e.  not expected sys.exit during logger.critical call during the test run). In this MR this issue is solved and the same logger is used for the app and testing session

Improvements:

1. Now there is no difference whether you get logger at the module level or inside the functions, due to the singleton pattern used in getting the logger and  auto propogating the handlers from the convert2rhel logger.
2. The setup of the logger performed before each testing unit and logs are available in the tmpdir (fixture) with automatic teardown at the end of the testing session
3. Provide write access to the app root dir within the docker

TODO
- [x] fix existing places where the logger was called from inside each function

### CODE REVIEW

**Review by fellipeh — COMMENTED** [review]
Getting this error: 

```
==================================== ERRORS ====================================
____________________ ERROR at setup of test_package_version ____________________
Traceback (most recent call last):
  File "/data/convert2rhel/unit_tests/conftest.py", line 62, in pkg_root
    import pathlib2 as pathlib  # pylint: disable=import-error
ImportError: No module named pathlib2
===================== 132 passed, 1 error in 3.63 seconds ======================
make: *** [Makefile:52: tests] Error 1
```

**Review by fellipeh — DISMISSED** [review]
After removing the `.cache` and build the images again.. works fine!

**Comment by ZhukovGreen** [comment]
@oamg/convert2rhel hey, I'd like to ensure all of you will see these changes before the merge. Please read the title or/and do a code review!

**Review by fellipeh — APPROVED** [review]
LGTM

**Review by bocekm — APPROVED** [review]

**Pull request merged**
