### PR TITLE
Add missing distros to rpm description

### PR DESCRIPTION
**Pull request by bocekm**
The package description is missing distros that can be converted with the tool.

Jira Issues:

-

Checklist

- [ ] PR has been tested manually in a VM (either author or reviewer)
- [ ] Jira issue has been made public if possible
- [ ] `[RHELC-]` or `[HMS-]` is part of the PR title 
- [ ] GitHub label has been added to help with Release notes 
- [ ] PR title explains the change from the user's point of view
- [ ] Code and tests are documented properly
- [ ] The commits are squashed to as few commits as possible (without losing data) 
- [ ] When merged: Jira issue has been updated to `Release Pending` if relevant

### CODE REVIEW

**Review by Venefilyn — APPROVED** [review]

**Comment by Venefilyn** [comment]
@bocekm @bookwar do we want to update this description for the downstream release?

**Comment by bocekm** [comment]
@Venefilym, you mean creating a hotfix downstream release 2.1.1? I don't think that's worth it. I'd just merge it in upstream and release it with 2.2.0.

**Comment by Venefilyn** [comment]
@bocekm No I meant modifying the description for future releases so that it showcases what Red Hat supports in the downstream release

**Comment by bocekm** [comment]
When we do a downstream release, we always pull the latest upstream spec file (or at least that's what we have in the downstream release instructions).
```
wget https://raw.githubusercontent.com/oamg/convert2rhel/main/packaging/convert2rhel.spec
```
So there's no need to update the description in the downstream dist-git repo.

**Review by pr-watson — APPROVED** [review]

**Pull request merged**
