### PR TITLE
[RHELC-1426] Drop support for 8.6 EUS conversions

### PR DESCRIPTION
**Pull request by r0x0d**
Deprecated the 8.6 EUS conversion, and removing the automatic detection of EUS systems.

From now on, users will be required to use --eus switch to identify their systems as EUS.

Jira Issues: [RHELC-1426](https://issues.redhat.com/browse/RHELC-1426)

Checklist

- [ ] PR has been tested manually in a VM (either author or reviewer)
- [ ] Jira issue has been made public if possible
- [ ] `[RHELC-]` is part of the PR title 
- [ ] GitHub label has been added to help with Release notes 
- [ ] PR title explains the change from the user's point of view
- [ ] Code and tests are documented properly
- [ ] The commits are squashed to as few commits as possible (without losing data) 
- [ ] When merged: Jira issue has been updated to `Release Pending` if relevant

### CODE REVIEW

**Comment by r0x0d** [comment]
I will wait for @danmyway or @kokesak to adapt the integration test portion of this PR, as it is a lot of unknown stuff for me and I'm afraid of messing things up.

**Review by SpyTec — CHANGES_REQUESTED** [review]
For this PR, I know it's a bit of work. But can we split the deprecation of 8.6 to a different PR? Or the other way around as that seems like less work

**Comment by r0x0d** [comment]
> For this PR, I know it's a bit of work. But can we split the deprecation of 8.6 to a different PR?

Sure, I can take care of that

**Comment by r0x0d** [comment]
TODO: Rework on this at some point this/next week

**Review by SpyTec — APPROVED** [review]
LGTM!

**Comment by SpyTec** [comment]
@r0x0d do we want to wait a bit before merging this just so we don't get integration tests failing for every PR while 8.6 integration tests still exist?

**Comment by r0x0d** [comment]
> @r0x0d do we want to wait a bit before merging this just so we don't get integration tests failing for every PR while 8.6 integration tests still exist?

Let's check with @danmyway first, and if he says it is okay, then we can go ahead.

**Review by kokesak — APPROVED** [review]
LGTM!

**Review by kokesak — APPROVED** [review]

**Pull request merged**
