### PR TITLE
[RHELC-1104] Change the id separator in the cli report to match what will be displayed in the insights webUI

### PR DESCRIPTION
**Pull request by abadger**
Jira Issues: [RHELC-1104](https://issues.redhat.com/browse/RHELC-1104)

Checklist

- [ ] PR has been tested manually in a VM (either author or reviewer)
- [x] Jira issue has been made public if possible
- [x] `[RHELC-]` is part of the PR title 
- [x] GitHub label has been added to help with Release notes 
- [x] PR title explains the change from the user's point of view
- [x] Code and tests are documented properly
- [x] The commits are squashed to as few commits as possible (without losing data) 
- [ ] When merged: Jira issue has been updated to `Release Pending` if relevant

### CODE REVIEW

**Review by SpyTec — APPROVED** [review]
LGTM. Unsure if integration tests need to be updated

**Comment by r0x0d** [comment]
This PR will cause a minor conflict with https://github.com/oamg/convert2rhel/pull/879/files. Making this comment here as a reminder for myself.

**Review by r0x0d — APPROVED** [review]
looks good

**Comment by abadger** [comment]
> LGTM. Unsure if integration tests need to be updated

Looks like integration tests do need to be updated.  Trying to figure out a way to grep for the places I need to update.....

**Comment by danmyway** [comment]
The failing tests were caused by a race condition, I will push a reliability hardening to a different PR.
Rerun the failed non-destructive suite.
Results here http://artifacts.osci.redhat.com/testing-farm/a43d1c5f-9986-4e53-aeb3-66dd28fcc54e/
```
+--------------------------------------+-----------------+-----------------+---------------------------------------------+--------+
| UUID                                 | Target          | Test Plan       | Test Case                                   | Result |
+--------------------------------------+-----------------+-----------------+---------------------------------------------+--------+
| a43d1c5f-9986-4e53-aeb3-66dd28fcc54e | CentOS-8-latest |                 |                                             |        |
|                                      |                 | non-destructive |                                             | PASSED |
|                                      |                 |                 | failures_and_skips_in_report                | PASSED |
|                                      |                 |                 | successful_report                           | PASSED |
|                                      |                 |                 | clean_cache                                 | PASSED |
|                                      |                 |                 | c2r_version_latest_or_newer                 | PASSED |
|                                      |                 |                 | c2r_version_older_no_envar                  | PASSED |
|                                      |                 |                 | c2r_version_older_with_envar                | PASSED |
|                                      |                 |                 | data_collection_acknowledgement             | PASSED |
|                                      |                 |                 | disable_data_collection                     | PASSED |
|                                      |                 |                 | incomplete_rollback_in_analyze              | PASSED |
|                                      |                 |                 | log_file_exists                             | PASSED |
|                                      |                 |                 | log_rhsm_error                              | PASSED |
|                                      |                 |                 | manpage                                     | PASSED |
|                                      |                 |                 | root_privileges                             | PASSED |
|                                      |                 |                 | smoke                                       | PASSED |
|                                      |                 |                 | variant_message                             | PASSED |
|                                      |                 |                 | config_cli_priority                         | PASSED |
|                                      |                 |                 | config_custom_path_custom_filename          | PASSED |
|                                      |                 |                 | config_custom_path_standard_filename        | PASSED |
|                                      |                 |                 | config_password_file_priority               | PASSED |
|                                      |                 |                 | config_standard_paths_priority              | PASSED |
|                                      |                 |                 | config_standard_paths_priority_diff_methods | PASSED |
|                                      |                 |                 | custom_kernel                               | PASSED |
|                                      |                 |                 | custom_invalid_repo_provided                | PASSED |
|                                      |                 |                 | custom_valid_repo_provided                  | PASSED |
|                                      |                 |                 | passing_activation_key_to_submgr            | PASSED |
|                                      |                 |                 | passing_password_to_submgr                  | PASSED |
|                                      |                 |                 | available_connection                        | PASSED |
|                                      |                 |                 | unavailable_connection                      | PASSED |
|                                      |                 |                 | custom_module_loaded                        | PASSED |
|                                      |                 |                 | custom_module_not_loaded                    | PASSED |
|                                      |                 |                 | unsupported_kmod_with_envar                 | PASSED |
|                                      |                 |                 | force_loaded_kmod                           | PASSED |
|                                      |                 |                 | tainted_kernel                              | PASSED |
|                                      |                 |                 | failed_repoquery                            | PASSED |
|                                      |                 |                 | yum_excld_kernel                            | PASSED |
|                                      |                 |                 | logfile_starts_with_command                 | PASSED |
|                                      |                 |                 | modified_releasever_in_configs              | PASSED |
|                                      |                 |                 | modified_releasever_to_unknown_release      | PASSED |
|                                      |                 |                 | packages_untracked_forced_rollback          | PASSED |
|                                      |                 |                 | packages_untracked_graceful_rollback        | PASSED |
|                                      |                 |                 | rhsm_cleanup                                | PASSED |
|                                      |                 |                 | terminate_on_password                       | PASSED |
|                                      |                 |                 | registration_start                          | PASSED |
|                                      |                 |                 | registration_success                        | PASSED |
|                                      |                 |                 | terminate_on_username                       | PASSED |
|                                      |                 |                 | package_download_error                      | PASSED |
|                                      |                 |                 | validating_packages_with_in_name_period     | PASSED |
|                                      |                 |                 | sub-man-rollback                            | PASSED |
|                                      |                 |                 | missing_system_release                      | PASSED |
|                                      |                 |                 | backup_os_release_no_envar                  | PASSED |
|                                      |                 |                 | backup_os_release_with_envar                | PASSED |
|                                      |                 |                 | unsuccessful_satellite_registration         | PASSED |
|                                      |                 |                 | empty_username_and_password                 | PASSED |
+--------------------------------------+-----------------+-----------------+---------------------------------------------+--------+

```

**Comment by abadger** [comment]
Thank you so much, @danmyway !  Reviews have been done, integration tests passing, and no new integration tests needed.  I'm merging this now.

**Pull request merged**
