### PR TITLE
Introduce packit

### PR DESCRIPTION
**Pull request by bocekm**
.. in order to automate:
  - CD in Copr
  - testing
  - EPEL releases in dist-git
  - we'll see what more

### CODE REVIEW

**Comment by bocekm** [comment]
@dhodovsk, how can I setup packit to build the packages in the https://copr.fedorainfracloud.org/coprs/g/oamg/convert2rhel Copr project?
I'd like the builds to be created for each PR and merge to master, and to have the builds a certain release (which I currently handle by [this Makefile](https://github.com/oamg/convert2rhel/blob/master/.copr/Makefile)). Thanks.

**Comment by dhodovsk** [comment]
it should be possible from CLI but there seems to be a bug now https://github.com/packit-service/packit/issues/686. Via service, I think packit-service would have to have permissions to the project.

For the versioning - can some of these options help: https://packit.dev/docs/actions/?

**Comment by bocekm** [comment]
@dhodovsk, the epel7 checks are marked as pending and it seems it's never gonna change. Could you please check why is the status not updated to either failure or success?

**Comment by dhodovsk** [comment]
Reason for the check not being set - https://github.com/packit-service/packit-service/issues/375

**Comment by bocekm** [comment]
The testing farm issue is being tracked here: https://gitlab.com/testing-farm/cruncher/issues/2

**Comment by thrix** [comment]
Retesting as I need fresh run ...

**Comment by thrix** [comment]
@TomasTomecek I am hitting an interesting issue here, the PR is opened from a fork, which means the commit id cannot be found :) Should not packit send Testing Farm in this case the fork repo?

```
        "git-url": "https://github.com/oamg/convert2rhel",
```
?

**Comment by thrix** [comment]
> @TomasTomecek I am hitting an interesting issue here, the PR is opened from a fork, which means the commit id cannot be found :) Should not packit send Testing Farm in this case the fork repo?
> 
> ```
>         "git-url": "https://github.com/oamg/convert2rhel",
> ```
> 
> ?

will open it as an issue ...

**Comment by thrix** [comment]
> > @TomasTomecek I am hitting an interesting issue here, the PR is opened from a fork, which means the commit id cannot be found :) Should not packit send Testing Farm in this case the fork repo?
> > ```
> >         "git-url": "https://github.com/oamg/convert2rhel",
> > ```
> > 
> > 
> > ?
> 
> will open it as an issue ...

Filled here: https://github.com/packit-service/packit/issues/700

**Comment by thrix** [comment]
@bocekm from testing POW, I have deployed all the fixes, if packit get's resolved, you should see a failed result:

```
[19:23:58] [+] [cruncher] [/plans/smoke] [prepare] Using cloned repository as working directory on the test machine
[19:23:58] [+] [cruncher] [/plans/smoke] [prepare] Installing builds from copr
# cd /etc/yum.repos.d && curl -LO https://copr.fedorainfracloud.org/coprs/packit/oamg-convert2rhel-11/repo/epel-6/oamg-convert2rhel-11-epel-6.repo
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
103   413  103   413    0     0    291      0  0:00:01  0:00:01 --:--:--   983
# repoquery --disablerepo=* --enablerepo=copr:copr.fedorainfracloud.org:packit:oamg-convert2rhel-11 '*' | grep -v \.src | xargs dnf -y install
Loaded plugins: fastestmirror, presto
Setting up Install Process
Loading mirror speeds from cached hostfile
 * base: ftp.sh.cvut.cz
 * epel: mirror.hosting90.cz
 * extras: ftp.sh.cvut.cz
 * updates: ftp.sh.cvut.cz
Resolving Dependencies
--> Running transaction check
---> Package convert2rhel.noarch 0:0.9-1.el6 will be installed
--> Processing Dependency: python-dateutil for package: convert2rhel-0.9-1.el6.noarch
--> Processing Dependency: python-decorator for package: convert2rhel-0.9-1.el6.noarch
--> Processing Dependency: python-dmidecode for package: convert2rhel-0.9-1.el6.noarch
--> Processing Dependency: python-ethtool for package: convert2rhel-0.9-1.el6.noarch
--> Processing Dependency: usermode for package: convert2rhel-0.9-1.el6.noarch
--> Processing Dependency: virt-what for package: convert2rhel-0.9-1.el6.noarch
--> Running transaction check
---> Package python-dateutil.noarch 0:1.4.1-7.el6 will be installed
---> Package python-decorator.noarch 0:3.0.1-3.1.el6 will be installed
---> Package python-dmidecode.x86_64 0:3.10.15-2.el6 will be installed
---> Package python-ethtool.x86_64 0:0.6-6.el6 will be installed
--> Processing Dependency: libnl.so.1()(64bit) for package: python-ethtool-0.6-6.el6.x86_64
---> Package usermode.x86_64 0:1.102-3.el6 will be installed
---> Package virt-what.x86_64 0:1.11-1.3.el6 will be installed
--> Running transaction check
---> Package libnl.x86_64 0:1.1.4-2.el6 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package          Arch   Version       Repository                          Size
================================================================================
Installing:
 convert2rhel     noarch 0.9-1.el6     copr:copr.fedorainfracloud.org:packit:oamg-convert2rhel-11
                                                                           74 k
Installing for dependencies:
 libnl            x86_64 1.1.4-2.el6   base                               121 k
 python-dateutil  noarch 1.4.1-7.el6   base                                84 k
 python-decorator noarch 3.0.1-3.1.el6 base                                14 k
 python-dmidecode x86_64 3.10.15-2.el6 base                                80 k
 python-ethtool   x86_64 0.6-6.el6     base                                31 k
 usermode         x86_64 1.102-3.el6   base                               187 k
 virt-what        x86_64 1.11-1.3.el6  base                                25 k

Transaction Summary
================================================================================
Install       8 Package(s)

Total download size: 615 k
Installed size: 2.1 M
Downloading Packages:
Setting up and reading Presto delta metadata
Processing delta metadata
Package(s) data still to download: 615 k
--------------------------------------------------------------------------------
Total                                           206 kB/s | 615 kB     00:02     
warning: rpmts_HdrFromFdno: Header V3 RSA/SHA1 Signature, key ID ff16cdde: NOKEY
Retrieving key from https://download.copr.fedorainfracloud.org/results/packit/oamg-convert2rhel-11/pubkey.gpg
Importing GPG key 0xFF16CDDE:
 Userid: "packit_oamg-convert2rhel-11 (None) <packit#oamg-convert2rhel-11@copr.fedorahosted.org>"
 From  : https://download.copr.fedorainfracloud.org/results/packit/oamg-convert2rhel-11/pubkey.gpg
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
  Installing : usermode-1.102-3.el6.x86_64                                  1/8 
  Installing : python-decorator-3.0.1-3.1.el6.noarch                        2/8 
  Installing : python-dateutil-1.4.1-7.el6.noarch                           3/8 
  Installing : virt-what-1.11-1.3.el6.x86_64                                4/8 
  Installing : libnl-1.1.4-2.el6.x86_64                                     5/8 
  Installing : python-ethtool-0.6-6.el6.x86_64                              6/8 
  Installing : python-dmidecode-3.10.15-2.el6.x86_64                        7/8 
  Installing : convert2rhel-0.9-1.el6.noarch                                8/8 
  Verifying  : python-dmidecode-3.10.15-2.el6.x86_64                        1/8 
  Verifying  : libnl-1.1.4-2.el6.x86_64                                     2/8 
  Verifying  : virt-what-1.11-1.3.el6.x86_64                                3/8 
  Verifying  : python-ethtool-0.6-6.el6.x86_64                              4/8 
  Verifying  : python-dateutil-1.4.1-7.el6.noarch                           5/8 
  Verifying  : convert2rhel-0.9-1.el6.noarch                                6/8 
  Verifying  : python-decorator-3.0.1-3.1.el6.noarch                        7/8 
  Verifying  : usermode-1.102-3.el6.x86_64                                  8/8 

Installed:
  convert2rhel.noarch 0:0.9-1.el6                                               

Dependency Installed:
  libnl.x86_64 0:1.1.4-2.el6                                                    
  python-dateutil.noarch 0:1.4.1-7.el6                                          
  python-decorator.noarch 0:3.0.1-3.1.el6                                       
  python-dmidecode.x86_64 0:3.10.15-2.el6                                       
  python-ethtool.x86_64 0:0.6-6.el6                                             
  usermode.x86_64 0:1.102-3.el6                                                 
  virt-what.x86_64 0:1.11-1.3.el6                                               

Complete!
[19:24:18] [+] [cruncher] [/plans/smoke] [execute] Running shell commands
# convert2rhel --help
Usage: 
  convert2rhel [-h]
  convert2rhel [-u username] [-p password | -f pswd_file] [--pool pool_id | -a] [--disablerepo repoid] [--enablerepo repoid] [-v variant] [--no-rpm-va] [--debug] [--restart] [-y]
  convert2rhel [--disable-submgr] [--disablerepo repoid] [--enablerepo repoid] [--no-rpm-va] [--debug] [--restart] [-y]
  convert2rhel [-k key] [-o organization] [--pool pool_id | -a] [--disablerepo repoid] [--enablerepo repoid] [-v variant] [--no-rpm-va] [--debug] [--restart] [-y]

Options:
  -h, --help            Show  help message and exit.
  --debug               Print traceback in case of an abnormal exit and
                        messages that could help find an issue.
  --no-rpm-va           Skip verification of RPM files using 'rpm -Va'. By
                        default the verification is performed and its output
                        is stored in a log file.
  --enablerepo=repoidglob
                        Enable specific repositories by ID or glob. Use this
                        option multiple times to add many repositories.
  --disablerepo=repoidglob
                        Disable specific repositories by ID or glob. Use this
                        option multiple times to add many repositories.

  Subscription Manager Options:
    The following options are specific tousing subscription-manager.

    -u USERNAME, --username=USERNAME
                        Username for the subscription-manager. If neither
                        --username nor --activation-key option is used, the
                        user is asked to enter the username.
    -p PASSWORD, --password=PASSWORD
                        Password for the subscription-manager. If --password,
                        --password-from-file or --activationkey are not used,
                        the user is asked to enter the password.
    -f PASSWORD_FROM_FILE, --password-from-file=PASSWORD_FROM_FILE
                        File containing password for the subscription-manager
                        in the plain text form. It's an alternative to the
                        --password option.
    -k ACTIVATIONKEY, --activationkey=ACTIVATIONKEY
                        Activation key used for the system registration by the
                        subscription-manager. It requires to have the --org
                        option specified.
    -o ORG, --org=ORG   Organization with which the system will be registered
                        by the subscription-manager. A list of available
                        organizations is possible to obtain by running
                        'subscription-manager orgs'. From the listed pairs
                        Name:Key, use the Key here.
    -a, --auto-attach   Automatically attach compatible subscriptions to the
                        system.
    --pool=POOL         Subscription pool ID. If not used, the user is asked
                        to choose from the available subscriptions. A list of
                        the available subscriptions is possible to obtain by
                        running 'subscription-manager list --available'.
    -v VARIANT, --variant=VARIANT
                        The RHEL variant to which the system will be
                        converted. Available variants are: Server, Client,
                        Workstation, ComputeNode for conversions from
                        CentOS/OL 6/7, Server, and Client for conversions from
                        CentOS/OL 5. If not used, the user is asked to choose
                        a variant.

  Alternative Installation Options:
    The following options are required if you do not intend on using
    subscription-manager

    --disable-submgr    Do not use the subscription-manager, use custom
                        repositories instead. See --enablerepo/--disablerepo
                        options. Without this option, the subscription-manager
                        is used to access RHEL repositories by default.

  Automation Options:
    The following options are used to automate the installation

    -r, --restart       Restart the system when it is successfully converted
                        to RHEL to boot the new RHEL kernel.
    -y                  Answer yes to all yes/no questions the tool asks.


[19:24:18] [E] [cruncher] [/plans/smoke] Command 'cd ~/git-source; convert2rhel --help' failed with return code '1'
[19:24:19] [+] [cruncher] [/plans/smoke] [finish] Destroying test machine
[19:24:19] [+] [cruncher] Test results:
[
    {
        "name": "/plans/smoke",
        "result": "failed"
    }
]
[19:24:19] [+] [cruncher] [/plans/smoke] [finish] Destroying test machine
```

Note that the test fails, as seems `--help` returns non zero code ...

**Comment by thrix** [comment]
Errors not displayed seems a problem in Packit: https://github.com/packit-service/packit-service/issues/387

**Comment by thrix** [comment]
@bocekm btw you can workaround the packit problem if you open this PR from a branch from this repo, not from your fork ... not sure how long will it take to fix this ...

**Comment by thrix** [comment]
ok, so I was wrong, issue was not in packit, but us using git on target machine, which is quite old on centos6/7. I removed that and git is not required anymore. Retesting in a minute

**Comment by thrix** [comment]
@bocekm ok, it works now \o/

**Comment by bocekm** [comment]
@dhodovsk, the packit got stuck on _"Pending — Building RPM ..."_. Is it an infrastructure issue?

**Comment by TomasTomecek** [comment]
@bocekm fedora-messaging let us down, again; I just rescheduled the build

**Comment by bocekm** [comment]
Issue related to the failed tests: https://gitlab.com/testing-farm/cruncher/issues/3

**Comment by bocekm** [comment]
@dhodovsk, @TomasTomecek, I think I'm lost. I've removed the lines:
```
create_tarball_command: ["python2", "setup.py", "sdist", "--dist-dir", "."]
current_version_command: ["python2", "setup.py", "--version"]
```
and by that I made it even worse. I'd actually like to use the `setup.py sdist` as it makes the tarball smaller and with relevant files only. I just don't know how to tweak the version so that every copr build has a distinct (and higher from the yum/dnf POV) version so that the testing farm picks up the right build.

**Comment by bocekm** [comment]
@sturivny, I've added you as a collaborator.

**Comment by bocekm** [comment]
@TomasTomecek, the latest packit-built copr package has version `v0.9.25.g06b4dff-1 ` (using the updated versioning https://github.com/TomasTomecek/packit/commit/b1f9bed5e19651516a4a2e96a74f71ec9b915f94) but the testing farm has installed version `0.9-1` instead. From the yum point of view the latter is still considered "newer" hence the farm test is still installing the incorrect version.

**Comment by TomasTomecek** [comment]
@bocekm We have changed how packit treats version and release in spec file recently so hopefully you shouldn't run into that any more in the future https://github.com/packit-service/packit/pull/748 https://github.com/packit-service/packit/issues/693

It will take us a few days to deploy that in prod, so please stay tuned.

**Comment by lachmanfrantisek** [comment]
@bocekm is it now ok? It looks like it finally installed the right version in the testing-farm:

```
================================================================================Installing: convert2rhel noarch 0.9-1.el6 copr:copr.fedorainfracloud.org:packit:oamg-convert2rhel-11 74 kInstalling for dependencies: libnl x86_64 1.1.4-2.el6 base 121 k python-dateutil noarch 1.4.1-7.el6 base 84 k python-decorator noarch 3.0.1-3.1.el6 base 14 k python-dmidecode x86_64 3.10.15-2.el6 base 80 k python-ethtool x86_64 0.6-6.el6 base 31 k usermode x86_64 1.102-3.el6 base 187 k virt-what x86_64 1.11-1.3.el6 base 25 k
```

The only problem is that `convert2rhel --help` ended with return code `1`, is that right?

Do you support both `-h` and `--help`?

```
# convert2rhel --help
Usage:
convert2rhel [-h]
convert2rhel [-u username] [-p password | -f pswd_file] [--pool pool_id | -a] [--disablerepo repoid] [--enablerepo repoid] [-v variant] [--no-rpm-va] [--debug] [--restart] [-y]
convert2rhel [--disable-submgr] [--disablerepo repoid] [--enablerepo repoid] [--no-rpm-va] [--debug] [--restart] [-y]
convert2rhel [-k key] [-o organization] [--pool pool_id | -a] [--disablerepo repoid] [--enablerepo repoid] [-v variant] [--no-rpm-va] [--debug] [--restart] [-y]
Options:
-h, --help Show help message and exit.
:
:
```

**Comment by sturivny** [comment]
@lachmanfrantisek 
so it supports both `-h` and `--help`. 
But both have exit status `1` :)

**Comment by bocekm** [comment]
@lachmanfrantisek, @sturivny, unfortunately, the farm still installs the wrong version. It installs `convert2rhel-0.9-1.el6.noarch`, but, as you can see from the RPM build logs, e.g. https://prod.packit.dev/copr-build/2937/logs, the version that was supposed to be installed is `convert2rhel-v0.9-1.20200323142323893536.el6.noarch`.

**Comment by TomasTomecek** [comment]
```
$ rpmdev-vercmp convert2rhel-0.9-1.el6 convert2rhel-v0.9-1.20200323142323893536                                                                                  
WARNING: hyphen in release1: 0.9-1.el6
WARNING: hyphen in release2: v0.9-1.20200323142323893536

rpmdev-vercmp <epoch1> <ver1> <release1> <epoch2> <ver2> <release2>
rpmdev-vercmp <EVR1> <EVR2>
rpmdev-vercmp # with no arguments, prompt

Exit status is 0 if the EVR's are equal, 11 if EVR1 is newer, and 12 if EVR2
is newer.  Other exit statuses indicate problems.

convert2rhel-0.9-1.el6 > convert2rhel-v0.9-1.20200323142323893536
```

Please create a new PR.

**Comment by bocekm** [comment]
@TomasTomecek, I will try create a new PR. But it seems to me the issue is going to be the same there.

**Comment by TomasTomecek** [comment]
> @TomasTomecek, I will try to create a new PR. But it seems to me the issue is going to be the same there.
> 
> EDIT: New PR - #27.
> EDIT2: Cool, it worked.

never underestimate the devs ;) so glad it worked!

**Pull request closed without merging**
