### PR TITLE
Fix rpm build script on CentOS

### PR DESCRIPTION
**Pull request by fellipeh**
Changes on rpm build script to reflect the new project schema

Signed-off-by: Fellipe Henrique <fpedrosa@redhat.com>

### CODE REVIEW

**Comment by fellipeh** [comment]
@bocekm could you please take a look on these packit error? It's appear I don't have the right credentials..

**Comment by bocekm** [comment]
@lachmanfrantisek, @TomasTomecek, packit says that @fellipeh doesn't have write or admin permissions. But he has, through the [oamg organization](https://github.com/oamg/) membership. Is this behaviour intentional?

**Comment by bocekm** [comment]
@fellipeh, try commenting `/packit test` now.

**Comment by bocekm** [comment]
Hi @thrix. There's no copr build available for this PR, yet the testing farm tests passed. That seems to be because they actually installed master branch builds of convert2rhel. I don't think this command for picking up the right copr build executed by the testing farm [1][2] works as expected:
`# repoquery --disablerepo=* --enablerepo=copr:copr.fedorainfracloud.org:group_oamg:convert2rhel '*' | grep -v \.src | xargs dnf -y install`

Screenshot from 2020-05-14 16-04-23

[1] https://console-testing-farm.apps.ci.centos.org/pipeline/a5b8f9e6-7263-40d8-b793-d4482c3279ea
[2] https://console-testing-farm.apps.ci.centos.org/pipeline/205b71cd-ce60-4b92-bc78-b452d346ece6

**Comment by thrix** [comment]
Hi @bocekm 

> Hi @thrix. There's no copr build available for this PR, yet the testing farm tests passed.

That seems more like Packit problem. @TomasTomecek @lachmanfrantisek. Is there any reason why testing farm would be called without a copr build? :)

> That seems to be because they actually installed master branch builds of convert2rhel. I don't think this command for picking up the right copr build executed by the testing farm [1][2] works as expected:
# repoquery --disablerepo=* --enablerepo=copr:copr.fedorainfracloud.org:group_oamg:convert2rhel '*' | grep -v \.src | xargs dnf -y install

￼We do not install any master build, we install what packit gives us :) there is no way I can verify that information is correct, we are just a dumb service.

Of course, if the installation command is not correct, then we will fix it.

> EDIT: To no surprise, even for a PR where the PR copr builds are available (#46), the testing farm installed the master branch builds instead.

Oh really? that means our fixes with @csomh suck :(

> EDIT2: Reported here: https://gitlab.com/testing-farm/cruncher/-/issues/5

I will look at this, I thought we last time confirmed it works, but seems we were just wrong.

**Comment by fellipeh** [comment]
@bocekm I think we can move forward to review/merge these

**Comment by bocekm** [comment]
> Oh really? that means our fixes with @csomh suck :(

Oh, I remember now:
https://github.com/packit-service/packit-service/issues/523#issuecomment-611606130
The repoquery with the asterisk is still there, but just for epel:
https://gitlab.com/testing-farm/cruncher/-/blob/master/modules/cruncher.py#L416

**Comment by lachmanfrantisek** [comment]
> That seems more like Packit problem. @TomasTomecek @lachmanfrantisek. Is there any reason why testing farm would be called without a copr build? :)

Yes, there is an issue for this situation: https://github.com/packit-service/packit-service/issues/535

**Pull request merged**
