### PR TITLE
fix: Make Manifest read README.md properly

### PR DESCRIPTION
**Pull request by SpyTec**
Fixes build errors with missing README

### CODE REVIEW

**Comment by fellipeh** [comment]
When I trying to build, getting these error:
```
+ /usr/bin/python2 setup.py build
Traceback (most recent call last):
  File "setup.py", line 35, in <module>
    long_description=read('README.md'),
  File "setup.py", line 27, in read
    return open(os.path.join(os.path.dirname(__file__), fname)).read()
IOError: [Errno 2] No such file or directory: 'README.md'
```

**Comment by fellipeh** [comment]
I believe the problem  is here:
`open(os.path.join(os.path.dirname(__file__), fname)).read()`  the function `os.path.dirname(__file__)` returns nothing:
```bash
(Pdb) os.path.join(os.path.dirname(__file__), fname)
'README.md'
(Pdb) os.path.dirname(__file__)
''
```

You need to change it for these:

```python
def read(fname):
    return open(os.path.join(os.path.dirname(os.path.abspath(__file__)), fname)).read()
```

**Comment by SpyTec** [comment]
@fellipeh I wasn't able to reproduce it at all using different folder structures, and even the same Virtualbox.

Your suggestion seems to be right however, I'll commit a fix in a separate PR

**Pull request merged**
