### PR TITLE
Test fix: reinstall kernel package for epel8

### PR DESCRIPTION
**Pull request by danmyway**
* the test failed to reboot on epel8 due to bad reinstall
* the kernel-core package should be reinstalled, not kernel

### CODE REVIEW

**Comment by danmyway** [comment]
Finished pipeline logs
**Oracle-Linux-8.7-tier0**
http://artifacts.osci.redhat.com/testing-farm/6584dfdb-9360-4f8d-8cf9-e0da12061f8c/
* all **PASS**

**CentOS-7-latest**
http://artifacts.osci.redhat.com/testing-farm/9db3afd3-c53d-4492-ac28-7b44874be4b1/

**Oracle-Linux-7.9**
http://artifacts.osci.redhat.com/testing-farm/9d6231c1-f251-477f-987f-ecbc887bdcaa/
* FAILing `remove_all_submgr_pkgs` due to flaky RHSM unsuccessful registration

* FAILing `detect_correct_boot_partition`  - false negative
  * this test should only run for UEFI machines, triggered as a side-effect of manual trigger

**Review by r0x0d — APPROVED** [review]
Looks lovely, thanks!

**Pull request merged**
