### PR TITLE
[RHELC-1493] Add rhel 9 version support up to 9.10

### PR DESCRIPTION
**Pull request by pr-watson**
This PR adds rhel 9 versions up to 9.10 in systeminfo so customers can do conversions on all rhel 9 versions. 

Jira Issues:[RHELC-1493 ](https://issues.redhat.com/browse/RHELC-1493)

Checklist

- [ ] PR has been tested manually in a VM (either author or reviewer)
- [x] Jira issue has been made public if possible
- [x] `[RHELC-]` is part of the PR title 
- [x] GitHub label has been added to help with Release notes 
- [x] PR title explains the change from the user's point of view
- [x] Code and tests are documented properly
- [x] The commits are squashed to as few commits as possible (without losing data) 
- [ ] When merged: Jira issue has been updated to `Release Pending` if relevant

### CODE REVIEW

**Review by r0x0d — APPROVED** [review]

**Comment by SpyTec** [comment]
Unit tests need to be fixed

**Review by r0x0d — APPROVED** [review]

**Comment by pr-watson** [comment]
> Wondering if we should use tests-all instead of just tier0 here

@danmyway what do you think?

**Pull request merged**
