### PR TITLE
Collect logs

### PR DESCRIPTION
**Pull request by kokesak**
We need to collect some important system logs in `finish` testing stage in order to get more information about the reboot issue.

Ref. ticket: https://issues.redhat.com/browse/OAMG-6415

### CODE REVIEW

**Comment by kokesak** [comment]
The reboot issue has been solved in #432. I suppose we do not need to collect any logs at this stage anymore. This PR can be closed?

**Comment by bocekm** [comment]
We may need to collect logs later on, you never know. But ideally through artifact collection done by TMT or Testing Farm. It's not critical now but you can ask those teams if such a feature is planned.

**Pull request closed without merging**
